version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.nextjs
    volumes:
      - ./src/app:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production

  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    volumes:
      - ./src/app/api:/api
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production

